name: CI

on: [push, pull_request]

env:
  HPCX_PKG_NAME: hpcx-v2.5.0-gcc-MLNX_OFED_LINUX-4.7-1.0.0.1-ubuntu18.04-x86_64
  HPCX_PKG_LINK: http://www.mellanox.com/downloads/hpc/hpc-x/v2.5
  OPEN_UCX_LINK: https://github.com/openucx/ucx
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get HPCX
      run: wget "${HPCX_PKG_LINK}/${HPCX_PKG_NAME}.tbz" -P /tmp
    - name: Unpack HPCX
      run: cd /tmp && tar xjf "${HPCX_PKG_NAME}.tbz"
    - name: Get UCX
      run: git clone ${OPEN_UCX_LINK} /tmp/ucx
    - name: Build UCX
      run: cd /tmp/ucx && ./autogen.sh && ./contrib/configure-release --without-java --disable-numa --prefix $PWD/install && make -j install
    - uses: actions/checkout@v1
    - name: Build
      run: |
        source /tmp/${HPCX_PKG_NAME}/hpcx-init.sh; hpcx_load
        ./autogen.sh
        ./configure --prefix=$PWD/install --with-ucx=/tmp/ucx/install
        make -j`nproc` install
    - name: Build XCCL tests
      run: |
        source /tmp/${HPCX_PKG_NAME}/hpcx-init.sh; hpcx_load
        export LD_LIBRARY_PATH=/tmp/ucx/install/lib:$LD_LIBRARY_PATH
        export LIBRARY_PATH=/tmp/ucx/install/lib:$LIBRARY_PATH
        export CPATH=/tmp/ucx/install/lib:$CPATH
        make -C test
    - name: Test run
      run: |
        source /tmp/${HPCX_PKG_NAME}/hpcx-init.sh; hpcx_load
        export LD_LIBRARY_PATH=/tmp/ucx/install/lib:$LD_LIBRARY_PATH
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_bcast
        mpirun --oversubscribe -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_barrier

        mpirun --oversubscribe -x XCCL_TEAM_HIER_NODE_LEADER_RANK_ID=3 -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEAM_HIER_NODE_LEADER_RANK_ID=4 -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_bcast
        mpirun --oversubscribe -x XCCL_TEAM_HIER_NODE_LEADER_RANK_ID=5 -x XCCL_TEST_TLS=hier -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_barrier

        mpirun --oversubscribe -x XCCL_TEAM_UCX_ALLREDUCE_ALG_ID=0 -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEAM_UCX_ALLREDUCE_ALG_ID=1 -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allreduce
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_bcast
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_barrier
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoall
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoallv
        mpirun --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_allgather
        mpirun -x XCCL_TEAM_UCX_ALLTOALL_PAIRWISE_CHUNK=0 --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoall
        mpirun -x XCCL_TEAM_UCX_ALLTOALL_PAIRWISE_CHUNK=0 --oversubscribe -x XCCL_TEST_TLS=ucx -np 8 -H localhost:8 --bind-to none -mca coll ^hcoll ./test/test_mpi_alltoallv
